name: ?? ?äº¤ Bug
title: '[bug] '
description: è¯¦ç??„æ?è¿°ä?ä¸?Bug
labels: ['type: bug']

body:
  - type: markdown
    attributes:
      value: |
        ## é¦–å?è¯·é?è¯?
        1. è¯·å??œç´¢ [note-gen/issues](https://github.com/TW199501/note-gen/issues) ä¸­æ˜¯?¦å·²å­˜åœ¨æ­¤é—®é¢˜ã€?
        2. å°è?ä¸‹è½½?€?°ç??¬ç? note-gen å¹¶æ?è¯•æ˜¯?¦è?å­˜åœ¨æ­¤é—®é¢˜ã€?
        3. è¯·ç¡®ä¿è???App ?„é—®é¢˜ï??Œä???AI ?–ä»£?†ç??®é???
        4. è¯·æ??§æ?äº¤è?æ±‚è¯¦ç»†ç??è¿° Bugï¼Œæ?ä¾›å…¨?¢ç?ä¿¡æ¯??
        5. è¯·åœ¨ç¤¾åŒº?…å??„å?è¨€??

  - type: textarea
    id: description
    attributes:
      label: è¯¦ç??è¿°è¿™ä¸ª Bug
      description: è¯·è¯¦ç»†ç??è¿°è¿™ä¸ª Bugï¼Œå??¬é??°æ­¥éª¤ã€é??Ÿè?ä¸ºå?å®é?è¡Œä¸ºï¼Œå??œå¯ä»¥å»ºè®®é?å¸¦æˆª?¾æ?è§†é???
      placeholder: Bug description
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: note-gen ?ˆæœ¬
      placeholder: è¯·å¡«?™ä?å½“å?ä½¿ç”¨??note-gen ?ˆæœ¬??
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: ?ä?ç³»ç?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - Android
        - iOS
    validations:
      required: true

  - type: textarea
    id: log
    attributes:
      label: ?¥é??¥å?
      description: ?¯ä»¥?šè??³é”®?¼å‡ºå¼€?‘è€…å·¥?·ï?å°†æŠ¥?™ä¿¡?¯ç?è´´åœ¨æ­¤å???
      placeholder: Bug logs
